# Generated by Django 2.2.3 on 2019-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerconfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routeswitchconfig',
            old_name='config_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='routeswitchconfig',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
