# Generated by Django 2.2.3 on 2019-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerconfig', '0002_auto_20191113_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeswitchconfig',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='routeswitchconfig',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
