# Generated by Django 2.2.3 on 2019-10-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleServer',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('LAB', 'lab device'), ('PROD', 'production device')], default='PROD', max_length=4)),
                ('os_type', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('interface', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Device')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InterfaceMapper',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('lab_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='lab.DeviceInterface')),
                ('prod_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='lab.DeviceInterface')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolePort',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('console_port', models.IntegerField()),
                ('client_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Device')),
                ('console_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ConsoleServer')),
            ],
        ),
    ]
