# Generated by Django 2.2.7 on 2019-11-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deviceinterface',
            options={},
        ),
    ]
