# Generated by Django 2.2.8 on 2019-12-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20191202_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('port_prefix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsolePort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router_attachment', to='lab.Device')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.ConsoleServer')),
            ],
        ),
    ]
