# Generated by Django 2.2.7 on 2019-11-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('startswith', 'startswith'), ('endswith', 'endswith'), ('contains', 'contains'), ('equals', 'equals')], max_length=255)),
                ('value', models.CharField(max_length=500)),
                ('os', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hier.Lineage')),
            ],
        ),
    ]
